# Site settings
title: José Vitor
description: José Vitor Portfolio
keywords: professor, Xadrez, R, matemática
author: IMG_FSB
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://jvkiler.github.io/#" # the base hostname & protocol for your site
permalink: /:collection/:path/